name: Aben
authors: Darcy Manoel
homepage: https://github.com/Adde-Endless-Sky/Aben
license: GPL-3.0-or-later
version: 48ca89d98f992ed71c2492e210a980338f3d1d3d
shortDescription: Fills in space in the galaxy with a new alien species.
description: 'Beyond the reaches of ordinary space faring civilizations lie the cluster
  of systems afforded to the Aben. Impressive technological advancement contrasts
  the clear non expansionist nature of the Aben, they believe in cooperation between
  all life and rarely show signs of hostility.

  This plugin is part of the Adde Endless Sky collection.'
url: https://github.com/Adde-Endless-Sky/Aben/archive/48ca89d98f992ed71c2492e210a980338f3d1d3d.zip
iconUrl: https://github.com/Adde-Endless-Sky/Aben/raw/48ca89d98f992ed71c2492e210a980338f3d1d3d/icon.png
autoupdate:
  type: commit
  branch: main
  url: https://github.com/Adde-Endless-Sky/Aben/archive/$version.zip
  iconUrl: https://github.com/Adde-Endless-Sky/Aben/raw/$version/icon.png
