name: Aberrant Kahet Outfitter
authors: Nova.
homepage: https://github.com/Nova1422/plugins?tab=readme-ov-file#aberrantkahetoutfitter
license: ALL-RIGHTS-RESERVED
version: v1.0.2-aberrant.kahet.outfitter
shortDescription: Sells Kahet and Aberrant Outfits at Remnants and Avgi planets respectively.
description: Sells Kahet and Aberrant Outfits at Remnants and Avgi planets respectively.
url: https://github.com/Nova1422/plugins/releases/download/v1.0.2-aberrant.kahet.outfitter/aberrant.kahet.outfitter.zip
iconUrl: https://raw.githubusercontent.com/Nova1422/plugins/v1.0.2-aberrant.kahet.outfitter/myplugins/aberrant.kahet.outfitter/icon.png
autoupdate:
  type: tag
  regex: ^.*-aberrant.kahet.outfitter$
  url: https://github.com/Nova1422/plugins/releases/download/$version/aberrant.kahet.outfitter.zip
  iconUrl: https://raw.githubusercontent.com/Nova1422/plugins/$version/myplugins/aberrant.kahet.outfitter/icon.png
