name: AES Aben
authors: Darcy Manoel
homepage: https://github.com/Adde-Endless-Sky/AES-Aben
license: GPL-3.0-or-later
version: 3f569b3bf386981773b6a21b88542c039f5f5153
shortDescription: Fills in space in the galaxy with a new alien species.
description: New aliens that are incapable of spaceflight as far as the player is
  concerned, offers the player multiple missions in aiding the Aben which also benefit
  the player in turn.
url: https://github.com/Adde-Endless-Sky/AES-Aben/archive/3f569b3bf386981773b6a21b88542c039f5f5153.zip
iconUrl: https://github.com/Adde-Endless-Sky/AES-Aben/raw/3f569b3bf386981773b6a21b88542c039f5f5153/icon.png
autoupdate:
  type: commit
  url: https://github.com/Adde-Endless-Sky/AES-Aben/archive/$version.zip
  iconUrl: https://github.com/Adde-Endless-Sky/AES-Aben/raw/$version/icon.png
