name: AES Omnis
authors: Darcy Manoel
homepage: https://github.com/Adde-Endless-Sky/AES-Omnis
license: GPL-3.0-or-later
version: d4dc76ec0540ea56d5e28ccc0d26e17107bc7458
shortDescription: The most extensive all-content plugin to date, for development or
  fun.
description: The most extensive all-content plugin to date. It includes many opportunities
  to test balance or ship builds against AI driven ships or fleets, all vanilla content
  and the content of many plugins available to use to put together different ship
  builds. Many more tools are included into Omnis too!
url: https://github.com/Adde-Endless-Sky/AES-Omnis/archive/d4dc76ec0540ea56d5e28ccc0d26e17107bc7458.zip
iconUrl: https://github.com/Adde-Endless-Sky/AES-Omnis/raw/d4dc76ec0540ea56d5e28ccc0d26e17107bc7458/icon.png
autoupdate:
  type: commit
  branch: main
  url: https://github.com/Adde-Endless-Sky/AES-Omnis/archive/$version.zip
  iconUrl: https://github.com/Adde-Endless-Sky/AES-Omnis/raw/$version/icon.png
