name: Arion - Air Superiority
authors: Spectre907
homepage: https://github.com/Spectre907YT/Arion-Air_Superiority
license: GPL-3.0-or-later
version: 3.3.1
shortDescription: Plugin that adds a bunch of interesting things, mainly some modern
  military planes and weapons.
description: 'An Endless Sky plugin that adds a variety of things to endless sky,
  including:

  -Real life fighters

  -Real life bombers

  -Ace combat super planes

  -Xenonauts fighters

  -A bunch of new H2H weapons based on real life weapons

  -Advanced outfits

  -Specialized weapons

  -Superweapons

  -Custom capital ships

  -1 (or 2) new ''short campaigns'' and some new jobs

  -ETC

  Special thanks to 1010todd, yuyuko_saigyouji. and gefulltetaubenbrust for some of
  the sprites.

  '
url: https://github.com/Spectre907YT/Arion-Air_Superiority/archive/refs/tags/3.3.1.zip
iconUrl: https://raw.githubusercontent.com/Spectre907YT/Arion-Air_Superiority/3.3.1/icon.png
autoupdate:
  type: tag
  url: https://github.com/Spectre907YT/Arion-Air_Superiority/archive/refs/tags/$version.zip
  iconUrl: https://raw.githubusercontent.com/Spectre907YT/Arion-Air_Superiority/$version/icon.png
