name: Capture Augen
authors: Nova.
homepage: https://github.com/Nova1422/plugins/tree/main?tab=readme-ov-file#captureaugen
license: ALL-RIGHTS-RESERVED
version: v1.0.0-capture.augen
shortDescription: Lets you capture the Super Heavy gegno ship "Augen" without consequences.
description: Lets you capture the Super Heavy gegno ship "Augen" without consequences.
url: https://github.com/Nova1422/plugins/releases/download/v1.0.0-capture.augen/capture.augen.zip
iconUrl: https://raw.githubusercontent.com/Nova1422/plugins/v1.0.0-capture.augen/myplugins/capture.augen/icon.png
autoupdate:
  type: tag
  regex: ^.*-capture.augen$
  url: https://github.com/Nova1422/plugins/releases/download/$version/capture.augen.zip
  iconUrl: https://raw.githubusercontent.com/Nova1422/plugins/$version/myplugins/capture.augen/icon.png
