name: Capture Archons
authors: Nova.
homepage: https://github.com/Nova1422/plugins
license: ALL-RIGHTS-RESERVED
version: v1.1.0-capture.archons
shortDescription: Lets you capture Archon ships
description: Makes all the pre exisiting archons ship be captureable, also spawns
  archon ships every 10 minutes in the system "Hallownest".
url: https://github.com/Nova1422/plugins/releases/download/v1.1.0-capture.archons/capture.archons.zip
iconUrl: https://raw.githubusercontent.com/Nova1422/plugins/v1.1.0-capture.archons/myplugins/capture.archons/icon.png
autoupdate:
  type: tag
  regex: ^.*-capture.archons$
  url: https://github.com/Nova1422/plugins/releases/download/$version/capture.archons.zip
  iconUrl: https://raw.githubusercontent.com/Nova1422/plugins/$version/myplugins/capture.archons/icon.png
