name: combat.ai
authors: zuckung
homepage: https://github.com/zuckung/endless-sky-plugins
license: MIT
version: v1.0.10-combat.ai
shortDescription: Offers a mission to install a combat AI, which increases your ship
  stats based on combat experience.
description: Offers a mission to install a combat AI, which increases your ship stats
  based on combat experience. See the README for details.
url: https://github.com/zuckung/endless-sky-plugins/releases/download/v1.0.10-combat.ai/combat.ai.zip
iconUrl: https://raw.githubusercontent.com/zuckung/endless-sky-plugins/v1.0.10-combat.ai/myplugins/combat.ai/icon.png
autoupdate:
  type: tag
  regex: ^.*-combat.ai$
  url: https://github.com/zuckung/endless-sky-plugins/releases/download/$version/combat.ai.zip
  iconUrl: https://raw.githubusercontent.com/zuckung/endless-sky-plugins/$version/myplugins/combat.ai/icon.png
