name: control.station
authors: zuckung
homepage: https://github.com/zuckung/endless-sky-plugins
license: MIT
version: v1.0.7-control.station
shortDescription: Adds a station to the Sol system that offers administrative functions
  started by the job board.
description: Adds a station to the Sol system that offers administrative functions
  started by the job board. See the README for details.
url: https://github.com/zuckung/endless-sky-plugins/releases/download/v1.0.7-control.station/control.station.zip
iconUrl: https://raw.githubusercontent.com/zuckung/endless-sky-plugins/v1.0.7-control.station/myplugins/control.station/icon.png
autoupdate:
  type: tag
  regex: ^.*-control.station$
  url: https://github.com/zuckung/endless-sky-plugins/releases/download/$version/control.station.zip
  iconUrl: https://raw.githubusercontent.com/zuckung/endless-sky-plugins/$version/myplugins/control.station/icon.png
