name: Crisis in Management
authors: leklachu
homepage: https://github.com/leklachu/endless-sky-syndicate
license: CC-BY-SA-4.0
version: v0.9.1
shortDescription: Alternate start in Syndicate space, with a story parallel to the
  main plot.
description: Crisis in Management is an alternate start in the Syndicate, the story
  of a manger who quits managing and start piloting. Leave your failing company and
  take to the stars to escape repercussions, then find yourself in the background,
  behind the scenes of Endless Sky's main storyline. Beyond that, the same endless
  sky awaits.
url: https://github.com/leklachu/endless-sky-syndicate/releases/download/v0.9.1/crisis-in-management_v0.9.1.zip
iconUrl: https://raw.githubusercontent.com/leklachu/endless-sky-syndicate/master/icon.png
autoupdate:
  type: tag
  url: https://github.com/leklachu/endless-sky-syndicate/releases/download/$version/crisis-in-management_$version.zip
