name: Cromha Expansion Plugin
authors: '@OcelotWalrus/Cromha, @Lumbar527'
homepage: https://github.com/OcelotWalrus/Cromha-Expansion-plugin
license: GPL-3.0-or-later
version: v0.0.2
shortDescription: Galaxy expansion plugin with various original stuff like new storylines,
  ships & outfits, new concepts and systems as well as a new galaxy.
description: 'Adds a new civilization to the Korath Space (now named the ''Empire
  Space''): The Cromha Empire. Also known as ''The Empire'', it is a government that
  dirige a huge part of the north of the Milky Way. It also a very high advanced government.
  They are human but don''t directly have contact with human Merchants, they have
  contact with the Syndicate, the Republic but they don''t allow them to enter their
  territory. Know more about the plugin in the wiki! (or test the game yourself)'
url: https://github.com/OcelotWalrus/Cromha-Expansion-plugin/releases/download/v0.0.2/Cromha-Expansion-plugin.zip
iconUrl: https://github.com/OcelotWalrus/Cromha-Expansion-plugin/blob/v0.0.2/icon.png?raw=true
autoupdate:
  type: tag
  url: https://github.com/OcelotWalrus/Cromha-Expansion-plugin/releases/download/$version/Cromha-Expansion-plugin.zip
  iconUrl: https://github.com/OcelotWalrus/Cromha-Expansion-plugin/blob/$version/icon.png?raw=true
