name: Disable Free Worlds
authors: ziproot
homepage: https://github.com/ziproot/disable-free-worlds
license: CC0-1.0
version: '1.0'
shortDescription: Exactly what it says on the tin. Disables all events related to the main plot, along with the Pact Recon mission chain.
description: Exactly what it says on the tin. Disables all events related to the main plot, along with the Pact Recon mission chain.
url: https://github.com/ziproot/disable-free-worlds/archive/3dd174e3391fb00c44f4cc2f12149de709f95c5c.zip
iconURL: https://github.com/ziproot/disable-free-worlds/raw/3dd174e3391fb00c44f4cc2f12149de709f95c5c/icon.png
