name: Disable Aberrant Blockade
authors: Nova.
homepage: https://github.com/Nova1422/plugins/?tab=readme-ov-file#disableaberrantblockade
license: ALL-RIGHTS-RESERVED
version: v1.0.0-disable.aberrant.blockade
shortDescription: Disables Aberrant Blockades on Avgi planets.
description: Disables Aberrant Blockades on Avgi planets.
url: https://github.com/Nova1422/plugins/releases/download/v1.0.0-disable.aberrant.blockade/disable.aberrant.blockade.zip
iconUrl: https://raw.githubusercontent.com/Nova1422/plugins/v1.0.0-disable.aberrant.blockade/myplugins/disable.aberrant.blockade/icon.png
autoupdate:
  update_url: https://github.com/Nova1422/plugins.git
  type: tag
  regex: ^.*-disable.aberrant.blockade$
  url: https://github.com/Nova1422/plugins/releases/download/$version/disable.aberrant.blockade.zip
  iconUrl: https://raw.githubusercontent.com/Nova1422/plugins/$version/myplugins/disable.aberrant.blockade/icon.png
