name: Exporianes
authors: Bereskatuket (Kestrel1110)
homepage: https://github.com/kestrel1110/Exporianes
license: GPL-3.0-or-later
version: '2.2'
shortDescription: Adds a new race of T5 Aliens.
description: Adds a new race of T5 aliens to a new galaxy. They can be reached after
  completing the Emerald Sword missions and having a combat rating of 13.
url: https://github.com/kestrel1110/Exporianes/archive/2.2.zip
iconUrl: https://github.com/kestrel1110/Exporianes/raw/2.2/icon.png
autoupdate:
  type: tag
  url: https://github.com/kestrel1110/Exporianes/archive/$version.zip
  iconUrl: https://github.com/kestrel1110/Exporianes/raw/$version/icon.png
