name: Ganiom
authors: heasdir
homepage: https://github.com/heasdir/ganiom-galaxy
license: EPL-2.0
version: v0.03
shortDescription: Galaxy plugin for endless sky. 
description: This plugin adds 16 races.
Currently there are about 6. Those races are human, Foren, Gainen, Hisair, Kem relicnain, the between and Bruchaven. 
url: https://github.com/heasdir/ganiom-galaxy/releases/tag/v0.03.zip
iconUrl: https://raw.githubusercontent.com/heasdir/ganiom-galaxy/refs/tags/v0.03/icon.png
autoupdate:
  type: commit
  url: https://github.com/heasdir/ganiom-galaxy/releases/tag/$version.zip
  iconUrl: https://raw.githubusercontent.com/heasdir/ganiom-galaxy/refs/tags/$version/icon.png
