name: Ganiom
authors: heasdir
homepage: https://github.com/heasdir/ganiom-galaxy
license: EPL-2.0
version: v0.03
shortDescription: Adds a galaxy with 16 races, heavily in progress and inspired by Galactic War.
description: |
This plugin adds 16 races.
Currently there are about 6
The races are
Human
Foren
Gainen
Hisair
The Between
Serbajkil
url: https://github.com/heasdir/ganiom-galaxy/archive/refs/tags/v0.03.zip
iconUrl:  
autoupdate:
  type: tag
  url: https://github.com/heasdir/ganiom-galaxy/archive/refs/tags/$version.zip
