name: Ganiom
authors: heasdir
homepage: https://github.com/heasdir/ganiom-galaxy
license: EPL-2.0
version: v0.03
shortDescription: | Adds a galaxy with 16 races, heavily in progress and inspired by Galactic War.
description: |
This plugin adds 16 races.
Currently there are about 6
The races are
Human
Foren
Gainen
Hisair
The Between
Serbajkil
url: https://github.com/heasdir/ganiom-galaxy/releases/tag/v0.03
iconUrl: https://github.com/heasdir/ganiom-galaxy/blob/ab0a73d7a607c9ed2d6411219039fff36fa807a9/icon.png
autoupdate:
  type: tag
  url: https://github.com/heasdir/ganiom-galaxy/releases/tag/$version
