name: Mega Freight
authors: 1010todd
homepage: https://github.com/1010todd/Mega-Freight
license: GPL-3.0-or-later
version: e4d0daf5873250d4653034cecf58fba4589646a2
shortDescription: Adds several mostly civilian ships for you and npc merchants (and
  pirates) to use for more variety in human space. Updated to Unstable releases.
description: This plugin adds several civilian and some military ships to add some
  more variety to human space and beyond. Mostly focused around larger ships but also
  have smaller freighters and starter-level ships as well. Will be updated to be compatible
  with lastest unstable release.
url: https://github.com/1010todd/Mega-Freight/archive/e4d0daf5873250d4653034cecf58fba4589646a2.zip
iconUrl: https://github.com/1010todd/Mega-Freight/raw/e4d0daf5873250d4653034cecf58fba4589646a2/icon.png
autoupdate:
  type: commit
  url: https://github.com/1010todd/Mega-Freight/archive/$version.zip
  iconUrl: https://github.com/1010todd/Mega-Freight/raw/$version/icon.png
