name: Midnight Expansion
authors: Michael Arsollon
homepage: https://github.com/MidnightPlugins/Midnight-Expansion
license: GPL-3.0-or-later
version: 0.10.14.1.0
shortDescription: Plugin using ships, outfits, or other resources from plugins by
  other creators or derivatives of their original creations.
description: Expanded content derived from the plugins of other creators. Some contents
  may require other Midnight Plugins creations.
url: https://github.com/MidnightPlugins/Midnight-Expansion/releases/download/0.10.14.1.0/Midnight.Expansion-0.10.14.1.0.zip
iconUrl: https://raw.githubusercontent.com/MidnightPlugins/Midnight-Expansion/0.10.14.1.0/icon.png
autoupdate:
  type: tag
  url: https://github.com/MidnightPlugins/Midnight-Expansion/releases/download/$version/Midnight.Expansion-$version.zip
  iconUrl: https://raw.githubusercontent.com/MidnightPlugins/Midnight-Expansion/$version/icon.png
