name: Midnight Scrapyard
authors: Michael Arsollon
homepage: https://github.com/MidnightPlugins/Midnight-Scrapyard
license: GPL-3.0-or-later
version: v.0.9.14.7.1
shortDescription: A plugin suggesting an epilogue for the Kor Sestor region of Endless Sky. Includes some new ships, outfits, and missions.
description: >- 
  This region of space has abandoned derelicts waiting to be scavenged. But something lurks amongst the wreckage...
url: https://github.com/MidnightPlugins/Midnight-Scrapyard/releases/download/v0.9.14.7.1/Midnight.Scrapyard-v0.9.14.7.1.zip
iconUrl: https://raw.githubusercontent.com/MidnightPlugins/Midnight-Scrapyard/v0.9.14.7.1/icon.png
autoupdate:
  type: tag
  url: https://github.com/MidnightPlugins/Midnight-Scrapyard/releases/download/$version/Lost.in.Midnight-$version.zip
  iconUrl: https://raw.githubusercontent.com/MidnightPlugins/Midnight-Scrapyard/$version/icon.png