name: mission.helper
authors: zuckung
homepage: https://github.com/zuckung/endless-sky-plugins
license: MIT
version: v1.0.10-mission.helper
shortDescription: Enables a job on every planet's job board, that shows missions you
  haven't done.
description: Enables a job on every planet's job board, that shows missions you haven't
  done. It also shows the 'source' and 'to offer' of these missions, so you can easily
  find them. See the README for details.
url: https://github.com/zuckung/endless-sky-plugins/releases/download/v1.0.10-mission.helper/mission.helper.zip
iconUrl: https://raw.githubusercontent.com/zuckung/endless-sky-plugins/v1.0.10-mission.helper/myplugins/mission.helper/icon.png
autoupdate:
  type: tag
  regex: ^.*-mission.helper$
  url: https://github.com/zuckung/endless-sky-plugins/releases/download/$version/mission.helper.zip
  iconUrl: https://raw.githubusercontent.com/zuckung/endless-sky-plugins/$version/myplugins/mission.helper/icon.png
