name: Obtain Heron
authors: Nova.
homepage: https://github.com/Nova1422/plugins?tab=readme-ov-file#obtainheron
license: ALL-RIGHTS-RESERVED
version: v1.0.4-obtainheron
shortDescription: Obtain the Superheavy Remnant ship, Heron, through a job board mission
  offered by any of the remnant planets.
description: Obtain the Superheavy Remnant ship, Heron, through a job board mission
  offered by any of the remnant planets.
url: https://github.com/Nova1422/plugins/releases/download/v1.0.4-obtainheron/obtainheron.zip
iconUrl: https://raw.githubusercontent.com/Nova1422/plugins/v1.0.4-obtainheron/myplugins/obtainheron/icon.png
autoupdate:
  type: tag
  regex: ^.*-obtainheron$
  update_url: https://github.com/Nova1422/plugins
  url: https://github.com/Nova1422/plugins/releases/download/$version/obtainheron.zip
  iconUrl: https://raw.githubusercontent.com/Nova1422/plugins/$version/myplugins/obtainheron/icon.png
