name: Omnis
authors: Darcy Manoel
homepage: https://github.com/Adde-Endless-Sky/-Omnis
license: GPL-3.0-or-later
version: b4f9bb7fb038690b15eeeace150db966c9a12c73
shortDescription: The most extensive all-content plugin to date, for development or
  fun.
description: 'The most extensive all-content plugin to date. All vanilla content and
  the content of many plugins available to use to put together different ship builds.
  Many more tools are included into Omnis too!

  This plugin is part of the Adde Endless Sky collection.'
url: https://github.com/Adde-Endless-Sky/-Omnis/archive/b4f9bb7fb038690b15eeeace150db966c9a12c73.zip
iconUrl: https://github.com/Adde-Endless-Sky/-Omnis/raw/b4f9bb7fb038690b15eeeace150db966c9a12c73/icon.png
autoupdate:
  type: commit
  branch: main
  url: https://github.com/Adde-Endless-Sky/-Omnis/archive/$version.zip
  iconUrl: https://github.com/Adde-Endless-Sky/-Omnis/raw/$version/icon.png
