name: Omnis
authors: Darcy Manoel
homepage: https://github.com/EndlessSkyCommunity/-Omnis
license: GPL-3.0-or-later
version: 346ebec1af1d9e7047f866a86147adc4a797fb5b
shortDescription: The most extensive all-content plugin to date, for development or
  fun.
description: 'The most extensive all-content plugin to date. All vanilla content and
  the content of many plugins available to use to put together different ship builds.
  Many more tools are included into Omnis too!

  This plugin is part of the Adde Endless Sky collection.'
url: https://github.com/EndlessSkyCommunity/-Omnis/archive/346ebec1af1d9e7047f866a86147adc4a797fb5b.zip
autoupdate:
  type: commit
  url: https://github.com/EndlessSkyCommunity/-Omnis/archive/$version.zip
