name: Prism Plugin
authors: Startingfresher
homepage: https://github.com/Startingfresher/Prism-Plug-in
license: GPL-3.0+
version: v1.0
shortDescription: Allows you to change your ship swizzle(colors, sort of) easily in game.
description: >- 
  The plugin adds missions on every star that let you change your fleet swizzle 
  to a few options. When you start the game you get access to two, eventually you 
  will find all 6. Look in the about.txt file for spoilers on where to get em. It should
  be mostly lore friendly.
url: https://github.com/Startingfresher/Prism-Plug-in/archive/refs/tags/v1.0.zip
autoupdate:
  type: tag
  url: https://github.com/Startingfresher/Prism-Plug-in/archive/refs/tags/$version.zip
