name: Quaernan Start
authors: Zoura the Quaernan Guy
homepage: https://github.com/AvianGeneticist/QuaernanHardpointsCarries
license: GPL-3.0
version: ea402025badbe3ac489c235452bf5e7ac64b086c
shortDescription: ES Custom start.  Quaernan Humans are a Tier 3 civilization with
  human expansionism at its peak around the 31st century; started by the Syndicate
  stoking innovation and to forestall a galactic recession.
description: An endless sky plugin that adds an extremely powerful set of ships and
  missions accessed via a custom start, intended for testing other extremely strong
  plugin factions or just generally playing around with.
url: https://github.com/AvianGeneticist/QuaernanHardpointsCarries/archive/ea402025badbe3ac489c235452bf5e7ac64b086c.zip
iconUrl: https://raw.githubusercontent.com/AvianGeneticist/QuaernanHardpointsCarries/ea402025badbe3ac489c235452bf5e7ac64b086c/icon%402x.png
autoupdate:
  type: commit
  url: https://github.com/AvianGeneticist/QuaernanHardpointsCarries/archive/$version.zip
  iconUrl: https://raw.githubusercontent.com/AvianGeneticist/QuaernanHardpointsCarries/$version/icon%402x.png
