name: Reduce Required Crew
authors: Nova.
homepage: https://github.com/Nova1422/plugins/?tab=readme-ov-file#purchaseableandroids
license: ALL-RIGHTS-RESERVED
version: v1.0.0-reduce.requiredcrew
shortDescription: Adds a free outfit which lets you reduce the required crew by 1.
description: Adds a free outfit which lets you reduce the required crew by 1.
url: https://github.com/Nova1422/plugins/releases/download/v1.0.0-reduce.requiredcrew/reduce.requiredcrew.zip
iconUrl: https://raw.githubusercontent.com/Nova1422/plugins/v1.0.0-reduce.requiredcrew/myplugins/reduce.requiredcrew/icon.png
autoupdate:
  type: tag
  regex: ^.*-reduce.requiredcrew$
  url: https://github.com/Nova1422/plugins/releases/download/$version/reduce.requiredcrew.zip
  iconUrl: https://raw.githubusercontent.com/Nova1422/plugins/$version/myplugins/reduce.requiredcrew/icon.png
