name: Rumskib
authors: TheGiraffe3
homepage: https://github.com/TheGiraffe3/rumskib/
license: CC-BY-SA-4.0
version: v0.11.0
shortDescription: Content expansion.
description: Rumskib is a large content expansion with ships, planets, missions, and
  more.
url: https://github.com/TheGiraffe3/rumskib/archive/refs/tags/v0.11.0.zip
iconUrl: https://github.com/TheGiraffe3/rumskib/raw/v0.11.0/icon.png
autoupdate:
  type: tag
  url: https://github.com/TheGiraffe3/rumskib/archive/refs/tags/$version.zip
  iconUrl: https://github.com/TheGiraffe3/rumskib/raw/$version/icon.png
