name: Solar.Sails
authors: TheronEpic
homepage: https://github.com/LixiChronikouOriou/ES-plugins/blob/main/README.md#SolarSails
license: CC-BY-SA-4.0
version: v2.1.2-Solar.Sails
shortDescription: Diffractive solar sails for Human and Coalition space, providing
  thrust, turn and solar collection, at that being outfitspace-efficient.
description: Epic diffractive solar sails for Human and Coalition space, providing
  thrust, turn and solar collection, at that using only outfitspace worth of half
  the consumed enginespace.
url: https://github.com/LixiChronikouOriou/ES-plugins/releases/download/v2.1.2-Solar.Sails/Solar.Sails.zip
iconUrl: https://raw.githubusercontent.com/LixiChronikouOriou/ES-plugins/v2.1.2-Solar.Sails/myplugins/Solar.Sails/icon.png
autoupdate:
  type: tag
  update_url: https://github.com/LixiChronikouOriou/ES-plugins/
  regex: ^.*-Solar.Sails$
  url: https://github.com/LixiChronikouOriou/ES-plugins/releases/download/$version/Solar.Sails.zip
  iconUrl: https://raw.githubusercontent.com/LixiChronikouOriou/ES-plugins/$version/myplugins/Solar.Sails/icon.png
