name: Tribute Quarg
authors: Nova.
homepage: https://github.com/Nova1422/plugins/tree/main/myplugins/tributequarg
license: ALL-RIGHTS-RESERVED
version: v1.0.2-tributequarg
shortDescription: Lets you tribute Quarg planets and ringworlds
description: Lets you tribute Quarg planets and ringworlds
url: https://github.com/Nova1422/plugins/releases/download/v1.0.2-tributequarg/tributequarg.zip
iconUrl: https://raw.githubusercontent.com/Nova1422/plugins/v1.0.2-tributequarg/myplugins/tributequarg/icon.png
autoupdate:
  type: tag
  regex: ^.*-tributequarg$
  update_url: https://github.com/Nova1422/plugins/
  url: https://github.com/Nova1422/plugins/releases/download/$version/tributequarg.zip
  iconUrl: https://raw.githubusercontent.com/Nova1422/plugins/$version/myplugins/tributequarg/icon.png
