name: uniques
authors: zuckung
homepage: https://github.com/zuckung/endless-sky-plugins
license: MIT
version: v1.0.13-uniques
shortDescription: Removes mass and outfit space from some uniques, puts others into
  unique category, or gives a png if there isn't one. Also adds lots of new uniques.
description: Removes mass and outfit space from some uniques, puts others into unique
  category, or gives a png if there isn't one. Also adds lots of new uniques. See
  the README for details.
url: https://github.com/zuckung/endless-sky-plugins/releases/download/v1.0.13-uniques/uniques.zip
iconUrl: https://raw.githubusercontent.com/zuckung/endless-sky-plugins/v1.0.13-uniques/myplugins/uniques/icon.png
autoupdate:
  type: tag
  regex: ^.*-uniques$
  url: https://github.com/zuckung/endless-sky-plugins/releases/download/$version/uniques.zip
  iconUrl: https://raw.githubusercontent.com/zuckung/endless-sky-plugins/$version/myplugins/uniques/icon.png
