name: World Forge
authors: Amazinite
homepage: https://github.com/EndlessSkyCommunity/world-forge
license: GPL-3.0-or-later
version: f453ce779612353bfa21c4093dd4905affd30230
shortDescription: A plugin for Endless Sky that allows the player to access everything
  in the game in one place.
description: A plugin for Endless Sky that allows the player to access everything
  in the game in one place. Includes features that the all-content plugin does not
  have such as the ability to boost your combat rating and change your friendly/hostile
  status with factions of the game without having to save-edit. Intended to help content
  creators test their plugins.
url: https://github.com/EndlessSkyCommunity/world-forge/archive/f453ce779612353bfa21c4093dd4905affd30230.zip
iconUrl: https://github.com/EndlessSkyCommunity/world-forge/raw/f453ce779612353bfa21c4093dd4905affd30230/icon.png
autoupdate:
  type: commit
  url: https://github.com/EndlessSkyCommunity/world-forge/archive/$version.zip
  iconUrl: https://github.com/EndlessSkyCommunity/world-forge/raw/$version/icon.png
