name: Wormholes
authors: ChemtrailOperator
homepage: https://github.com/chemtrailoperator/Wormholes_EndlessSky
license: GPL-3.0-or-later
version: v1.0
shortDescription: Become a galactic diplomat with wormhole access to anywhere.
description: This plugin adds a short storyline (with much more to come) to become a diplomat in Galactic Command, granting you access to a galactic network of wormholes with access to every faction.
url: https://github.com/chemtrailoperator/Wormholes_EndlessSky/releases/download/v1.0/Wormholes-v1.0.zip
iconUrl: https://github.com/chemtrailoperator/Wormholes_EndlessSky/raw/v1.0/icon.png
autoupdate:
  type: tag
  url: https://github.com/chemtrailoperator/Wormholes_EndlessSky/releases/download/$version/Wormholes-$version.zip
  iconUrl: https://github.com/chemtrailoperator/Wormholes_EndlessSky/raw/$version/icon.png
