name: Zoom Extension
authors: Nova.
homepage: https://github.com/Nova1422/plugins/tree/main?tab=readme-ov-file#zoomextension
license: ALL-RIGHTS-RESERVED
version: v1.0.0-zoom.extension
shortDescription: Lets you zoom out more.
description: Lets you zoom out or in, more than you can in vanilla.
url: https://github.com/Nova1422/plugins/releases/download/v1.0.0-zoom.extension/zoom.extension.zip
iconUrl: https://raw.githubusercontent.com/Nova1422/plugins/v1.0.0-zoom.extension/myplugins/zoom.extension/icon.png
autoupdate:
  type: tag
  regex: ^.*-zoom.extension$
  url: https://github.com/Nova1422/plugins/releases/download/$version/zoom.extension.zip
  iconUrl: https://raw.githubusercontent.com/Nova1422/plugins/$version/myplugins/zoom.extension/icon.png
