name: Generate files

on:
  push:
    branches:
    - master

jobs:
  generate:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo pip3 install setuptools wheel
        sudo pip3 install yq
        pip3 install -r scripts/requirements.txt
    - name: Generate plugins.yaml
      run: python scripts/generate_full_index.py manifests/ generated/plugins.yaml
    - name: Generate plugins.json
      run: yq '.' generated/plugins.yaml > generated/plugins.json
    - name: Generate individual JSON files
      run: |
        mkdir -p generated/plugins
        for f in manifests/*.yaml; do
          stripped=$(basename "$f" .yaml)
          yq '.' "$f" > "generated/plugins/$stripped.json"
        done
    - name: Generate PLUGINS.md
      run: python3 scripts/generate_table.py generated/plugins.yaml generated/PLUGINS.md
    - uses: stefanzweifel/git-auto-commit-action@v6.0.1
      if: github.repository == 'endless-sky/endless-sky-plugins'
      with:
        commit_message: "chore(regenerate): triggered by ${{ github.sha }}"
        file_pattern: ./generated/*
        commit_user_name: Generate files workflow
        commit_author: github-actions[bot] <actions@github.com>
    - name: Alert MCO on failure
      if: ${{ failure() }}
      uses: sarisia/actions-status-discord@v1
      with:
        webhook: ${{ secrets.DISCORD_WEBHOOK }}
